
#define JOB_AVAILABLE 0
#define JOB_UNAVAILABLE_GENERIC 1
#define JOB_UNAVAILABLE_BANNED 2
#define JOB_UNAVAILABLE_PLAYTIME 3
#define JOB_UNAVAILABLE_ACCOUNTAGE 4
#define JOB_UNAVAILABLE_SLOTFULL 5
#define JOB_UNAVAILABLE_GENERATION 6
#define JOB_UNAVAILABLE_MASQUERADE 7
#define JOB_UNAVAILABLE_SPECIES 8
#define JOB_UNAVAILABLE_SPECIES_LIMITED 9
#define JOB_UNAVAILABLE_CLAN 10
#define JOB_UNAVAILABLE_AGE 11
#define JOB_UNAVAILABLE_RANK 12
#define JOB_UNAVAILABLE_TRIBE 13
#define JOB_BLOCKED_SLOT 14

#define DEFAULT_RELIGION "Christianity"
#define DEFAULT_DEITY "Jesus"

#define JOB_DISPLAY_ORDER_DEFAULT 0

#define JOB_DISPLAY_ORDER_CITIZEN 1
#define JOB_DISPLAY_ORDER_ELDER 2
#define JOB_DISPLAY_ORDER_PRINCE 3
#define JOB_DISPLAY_ORDER_SHERIFF 4
#define JOB_DISPLAY_ORDER_CLERK 5
#define JOB_DISPLAY_ORDER_HOUND 6
#define JOB_DISPLAY_ORDER_MILSEC 7
#define JOB_DISPLAY_ORDER_BRUJAH 8
#define JOB_DISPLAY_ORDER_MALKAVIAN 9
#define JOB_DISPLAY_ORDER_NOSFERATU 10
#define JOB_DISPLAY_ORDER_TOREADOR 11
#define JOB_DISPLAY_ORDER_VENTRUE 12
#define JOB_DISPLAY_ORDER_GRAVEYARD 13
#define JOB_DISPLAY_ORDER_CHIEF_DOCTOR 14
#define JOB_DISPLAY_ORDER_DOCTOR 15
#define JOB_DISPLAY_ORDER_STREETJAN 16
#define JOB_DISPLAY_ORDER_STRIP 17
#define JOB_DISPLAY_ORDER_TAXI 18
#define JOB_DISPLAY_ORDER_TRIAD_DRAGON 19
#define JOB_DISPLAY_ORDER_TRIAD_STICK 20
#define JOB_DISPLAY_ORDER_TRIAD_WIND 21
#define JOB_DISPLAY_ORDER_TRIAD_MONK 22
#define JOB_DISPLAY_ORDER_GANGSTER 23
#define JOB_DISPLAY_ORDER_BARKEEPER 24
#define JOB_DISPLAY_ORDER_EMISSARY 25
#define JOB_DISPLAY_ORDER_SWEEPER 26
#define JOB_DISPLAY_ORDER_BRUISER 27
#define JOB_DISPLAY_ORDER_DEALER 28
#define JOB_DISPLAY_ORDER_SUPPLY 29
#define JOB_DISPLAY_ORDER_REGENT 30
#define JOB_DISPLAY_ORDER_ARCHIVIST 31
#define JOB_DISPLAY_ORDER_GIOVANNIELDER 32
#define JOB_DISPLAY_ORDER_GIOVANNICONSIG 33
#define JOB_DISPLAY_ORDER_GIOVANNI 34
#define JOB_DISPLAY_ORDER_GIOVANNIMAFIA 35
#define JOB_DISPLAY_ORDER_POLICE_LIEUTENANT 36
#define JOB_DISPLAY_ORDER_POLICE 37
#define JOB_DISPLAY_ORDER_POLICE_SERGEANT 38
#define JOB_DISPLAY_ORDER_POLICE_CORONER 39
#define JOB_DISPLAY_ORDER_FBI 40
#define JOB_DISPLAY_ORDER_VOIVODE 41
#define JOB_DISPLAY_ORDER_BOGATYR 42
#define JOB_DISPLAY_ORDER_ZADRUGA 43
#define JOB_DISPLAY_ORDER_ENDRONLEAD 44
#define JOB_DISPLAY_ORDER_ENDRONEXEC 45
#define JOB_DISPLAY_ORDER_ENDRONSECCHIEF 46
#define JOB_DISPLAY_ORDER_ENDRONSEC 47
#define JOB_DISPLAY_ORDER_ENDRON 48
#define JOB_DISPLAY_ORDER_PRIEST 49
#define JOB_DISPLAY_ORDER_REVEREND 50
#define JOB_DISPLAY_ORDER_ABBOT 51

#define JOB_DISPLAY_ORDER_WESTERNEYEVOICE 52
#define JOB_DISPLAY_ORDER_WESTERNEYEARM 53
#define JOB_DISPLAY_ORDER_WESTERNEYERANGER 54

#define JOB_DISPLAY_ORDER_SABBAT_PRIEST 55
#define JOB_DISPLAY_ORDER_SABBAT_DUCTUS 56
#define JOB_DISPLAY_ORDER_SABBAT 57

// #define JOB_DISPLAY_ORDER_INVESTIGATOR 25
// #define JOB_DISPLAY_ORDER_CHAPLAIN 26
